LVM-480 #comment made add/remove buttons of tutors and students consi…
LiteracyVolunteersOfMA/lvm-rails pull request #158
Opened 2017-10-24 16:43 UTC by avnighael

Made Add/remove buttons of tutors#show view and Set tutor button of students#show view consistent with other buttons.

2017-10-24 23:01 UTC, nabeel- requested changes
Looking good, just a couple of tweaks!

2017-10-24 23:01 UTC, nabeel- commented on app/views/tutors/show.html.erb
> +                            <%= button_tag(type: "submit", class: "btn btn-default") do %>
Let's stick to the convention of using `btn-danger` for destructive actions like removing a student.

2017-10-24 23:01 UTC, nabeel- commented on app/views/students/show.html.erb
> +                          Set Tutor <i class="icon-repeat"></i>
We use [Bootstrap's glyphicons](https://getbootstrap.com/docs/3.3/components/#glyphicons) for icons. To add an icon use `<i class="glyphicon glyphicon-whatever"></i>`

Let's also try to use icons that help describe the action. For example, `glyphicon-remove` for deletions, `glyphicon-plus` for additions, etc

2017-10-24 23:01 UTC, nabeel- commented on app/views/tutors/show.html.erb
> +                          Add Student <i class="icon-repeat"></i>
See comment above about icons

2017-10-24 23:01 UTC, nabeel- commented on app/views/tutors/show.html.erb
> +                                Remove Student <i class="icon-repeat"></i>
See above comment about icons

2017-12-05 23:54 UTC, kmcarol26 commented
No issues. Merging into master.

2017-12-05 23:55 UTC, merged