LVM-435 masking for Coordinator form
LiteracyVolunteersOfMA/lvm-rails pull request #97
Opened 2017-03-28 01:50 UTC by jlally21

implemented masking for phone number and email on coordinator form

2017-03-28 16:40 UTC, xingyif approved these changes

2017-03-28 17:05 UTC, zack requested changes
Your frontend and backend validations for phone number are now out of sync.

2017-03-30 11:36 UTC, zack approved these changes
wait what why did i say that?

2017-03-30 15:10 UTC, jlally21 commented
@zack  haha okay thanks...yeah i was going to ask you what you meant.

2017-03-30 15:13 UTC, merged